### ISSUE TITLE
Feature Requests: authentication sessions

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/genieparser#24]
Is it possible to add parer for show auth session commnad?
would be grate to have for validating  dot1x config and for finding failing dot1x devices.
Looking for parser compatible with the IOS platform, i believe the output is similar from other platforms.

more related commands can be find hear. ->
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/s1/sec-s1-xe-3se-3850-cr-book/sec-s1-xe-3se-3850-cr-book_chapter_01.html#wp3404908137

example commnad.
`show authentication sessions`
`show authentication sessions int gi 1/0/11`
`show authentication sessions interface GigabitEthernet3/0/2 details`

**Comment by thaing408** [comment]
Hi Peter,
I am looking into and get back to you.

Thanks,
--Thai.

**Comment by thaixuann** [comment]
Hi Peter,

It has been fixed, and a beta package has been released

pip install genie.libs.parser --upgrade --pre

Give it a try and let us know.

Thanks,
--Thai.

**Comment by urskog84** [comment]
Hi @thaixuann! i have finaly hade time to make a inistal test.
```
pip3 list | grep genie.libs.parser
genie.libs.parser            19.7.1b5
```
i now get a error, is ther parser incuded in 19.7.b5 ??
```
In [1]: sw1.parse("show authentication sessions")
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-23a5e1aa337f> in <module>
----> 1 sw1.parse("show authentication sessions")

/usr/local/lib64/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device.parse()

/usr/local/lib/python3.7/site-packages/genie/libs/parser/utils/common.py in get_parser(command, device)
     90             raise Exception("Could not find parser for "
     91                             "'{c}' under {l}".format(
---> 92                                 c=command, l=lookup._tokens)) from None
     93     else:
     94         # Regex world!

Exception: Could not find parser for 'show authentication sessions' under ('ios',)

```

**Comment by thaixuann** [comment]
Hi Peter,
Thanks for letting me know the issue. 
Can you please share the output of the commands from the device?

Thanks,
--Thai.

**Comment by urskog84** [comment]
My Band. the switch i tested the parser against had now sessions 😄 

```
In [4]: sw2.execute("show authentication sessions")
[2019-08-23 09:01:58,270] +++ tstipswi002: executing command 'show authentication sessions' +++
show authentication sessions
No sessions currently exist
tstipswi002#
Out[4]: 'No sessions currently exist'

In [5]: sw1.execute("show authentication sessions")
[2019-08-23 09:02:17,324] +++ tstipswi001: executing command 'show authentication sessions' +++
show authentication sessions
No sessions currently exist
tstipswi001#
Out[5]: 'No sessions currently exist'
```
would be nice if it return i empty object, or a bool value 'false' on empty/'true' when there are sessions in the list

**Comment by thaixuann** [comment]
Hello @urskog84,
We fixed the issue and genie package v19.9 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install genie --upgrade 

Let us know if there is any issue.

Thanks,
--Thai.

**Comment by micyew** [comment]
Hi @thaixuann,

I've NAC enabled in the access switch. When I use the "show authentication sessions <<interface>> details",  it generated an error " genie.metaparser.util.exceptions.SchemaUnsupportedKeyError: interfaces.GigabitEthernet1/0/1.mac_address.0050.b6d6.a8b0: **Unsupported keys: ['url_redirect_acl', 'acs_acl']**"

It seems that some of the keys are not supported.? DId I miss anythong? thakns..

The output of my NAC swtich show below...

c3850_NAC_SW#show authentication sessions interface GigabitEthernet1/0/1 details
            Interface:  GigabitEthernet1/0/1
               IIF-ID:  0x156E4683
          MAC Address:  0050.b6d6.a8b0
         IPv6 Address:  fe80::2119:3248:786b:40db
         IPv4 Address:  192.168.1.5
            User-Name:  00-50-B6-D6-A8-B0
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A76060A00000018DD109536
      Acct Session ID:  0x0000000f
               Handle:  0x0f00000e
       Current Policy:  POLICY_Gi1/0/1


Server Policies:
     **URL Redirect ACL**: ACLSWITCH_Redirect_v1
         **URL Redirect**: https://psn01.test.com.au:8446/portal/gateway?_sessionId_=0A76060A00000018DD109536&portal=bb98b6f0-20a1-11e6-a7cb-005056866918&action=cwa&token=98efdc0f68582db18d67fdaa4a46822c
              **ACS ACL: xACSACLx-IP-ACL_MABDefault_V3-5da428a4**

**Comment by thaixuann** [comment]
Hi @micyew<mailto:notifications@github.com>,
I will look into it and let you know once the issue is fixed.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by micyew** [comment]
Hi @thaixuann,

Found another bug in this "show authentication sessions" parser...It didn't pick up the "session_count" key as compare to "show access-session" parser. ie "show access-session" have the "session_count" key/value.

I would like to run thru' the NAC switches and find how many session are there for each switch...

**Comment by thaixuann** [comment]
Hello @micyew
Thanks for let us know the issue. I will look into and let you know once the issue is fixed.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment]
Hello @micyew ,

It has been fixed, and a beta package has been released

pip install genie.libs.parser --upgrade --pre

Give it a try and let us know.

Thanks,
--Thai.

**Comment by micyew** [comment]
Hi Thai,

I tried but still can't get the correct outcome. Did I miss anything? See
output below:

1. When I do a parse on "show authentication sessions", I still can't get
the "session_count" key as compare to "show access-session" parse?

(pyats) test@test_server:~/python_script/pyats_genie/genie_parsing/nac_session$
genie parse "show authentication sessions" --testbed-file testbed_1.yaml
  sys.exit(main())
  0%|

                                                              | 0/1
[00:00<?, ?it/s]{
  "interfaces": {
    "GigabitEthernet1/0/1": {
      "client": {
        "0050.b6d6.a8b0": {
          "client": "0050.b6d6.a8b0",
          "domain": "DATA",
          "method": "mab",
          "session": {
            "0A76060A00000018DD109536": {
              "session_id": "0A76060A00000018DD109536"
            }
          },
          "status": "Auth"
        }
      },
      "interface": "GigabitEthernet1/0/1"
    },
    "GigabitEthernet1/0/2": {
      "client": {
        "b4a8.b968.f35b": {
          "client": "b4a8.b968.f35b",
          "domain": "VOICE",
          "method": "mab",
          "session": {
            "0A76060A0000000D5323681F": {
              "session_id": "0A76060A0000000D5323681F"
            }
          },
          "status": "Auth"
        }
      },
      "interface": "GigabitEthernet1/0/2"
    }
  }
}


  2. When I do a parse on  "show authentication sessions interface
GigabitEthernet1/0/2 detail", I still can't get the downloadable ACL (ie.
ACS ACL) . I can see it in the actual switch CLI output...

##########
(pyats) test@test_server:~/python_script/pyats_genie/genie_parsing/nac_session$
genie parse "show authentication sessions interface GigabitEthernet1/0/2
detail" --testbed-file testbed_1.yaml
  sys.exit(main())
  0%|
 Parsed command 'show authentication sessions interface
GigabitEthernet1/0/1 detail' but it returned empty
#########

Output from my NAC switch:

NAC_c3850_SW#show authentication sessions interface GigabitEthernet1/0/2
detail
            Interface:  GigabitEthernet1/0/2
               IIF-ID:  0x17B5937E
          MAC Address:  b4a8.b968.f35b
         IPv6 Address:  Unknown
         IPv4 Address:  1.1.1.1
            User-Name:  B4-A8-B9-68-F3-5B
               Status:  Authorized
               Domain:  VOICE
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A76060A0000000D5323681F
      Acct Session ID:  0x00000004
               Handle:  0x90000003
       Current Policy:  POLICY_Gi1/0/2


Server Policies:
              *ACS ACL: xACSACLx-Test_ACL_CiscoPhones-583e3751*


Method status list:
       Method           State
        dot1x           Stopped
          mab           Authc Success


#####
3. I've install the pre libs.parser....Do I need to ugprade the rest of the
component? I can see all of them is in 19.10 version.....


(pyats) test@test_server:~/python_script/pyats_genie/genie_parsing/nac_session$
python -m pip list | egrep "genie|pyats"
disable this warning.
genie (19.10)
genie.abstract (19.10)
genie.conf (19.10)
genie.harness (19.10)
genie.libs.conf (19.10)
genie.libs.filetransferutils (19.10)
genie.libs.ops (19.10.1)
*genie.libs.parser (19.10.1b0) <<<<<<<<<<<<<<< upgrade to beta!!*
genie.libs.robot (19.10)
genie.libs.sdk (19.10)
genie.libs.telemetry (19.10)
genie.metaparser (19.10)
genie.ops (19.10)
genie.parsergen (19.10)
genie.predcore (19.10)
genie.telemetry (19.10)
genie.trafficgen (19.10)
genie.utils (19.10)
pyats (19.10)
pyats.aereport (19.10)
pyats.aetest (19.10)
pyats.async (19.10)
pyats.connections (19.10)
pyats.datastructures (19.10)
pyats.easypy (19.10.1)
pyats.kleenex (19.10)
pyats.log (19.10)
pyats.reporter (19.10)
pyats.results (19.10)
pyats.robot (19.10)
pyats.tcl (19.10)
pyats.topology (19.10)
pyats.utils (19.10)

**Comment by micyew** [comment]
Found some typo error for point (2)..It should be "details" (with a "s")
rather than "detail"..

But even if I ran it, the give an  Unsupported keys: ['acs_acl']  error....

(pyats) test@test_server:~/python_script/pyats_genie/genie_parsing/nac_session$
genie parse "show authentication sessions interface GigabitEthernet1/0/2*
details*" --testbed-file testbed_1.yaml
  sys.exit(main())
  0%|
Issue with the parser show authentication sessions interface
GigabitEthernet1/0/2 details

Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 289, in
genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 528, in
genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 289, in
genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in
genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 302, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 277, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 302, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 277, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 371, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 346, in
genie.metaparser.util.schemaengine.Schema.validate
  File "src/genie/metaparser/util/schemaengine.py", line 403, in
genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaUnsupportedKeyError:
interfaces.GigabitEthernet1/0/2.mac_address.b4a8.b968.f35b: Unsupported
keys: ['acs_acl']

**Comment by thaixuann** [comment]
Hi @micyew ,
Thanks for reporting. 
For issue #1, there is no "session_count" for the command. So that's why the parser does not produce one.
For issue #2, I am looking into it. I will let you know.

Thanks,
--Thai.

**Comment by micyew** [comment]
For issue #1 <https://github.com/CiscoTestAutomation/genieparser/issues/1> ,
below is the CLI "show authentication sessions" output from the NAC
switch...I can see the "Session count"...Seems the parser not parsing it?

NAC_c3850_SW#show authentication sessions
Interface                MAC Address    Method  Domain  Status Fg  Session
ID
--------------------------------------------------------------------------------------------
Gi1/0/1                  0050.b6d6.a8b0 mab     DATA    Auth
 0A76060A00000018DD109536
Gi1/0/2                  b4a8.b968.f35b mab     VOICE   Auth
 0A76060A0000000D5323681F

*Session count = 2*

Key to Session Events Blocked Status Flags:

  A - Applying Policy (multi-line status for details)
  D - Awaiting Deletion
  F - Final Removal in progress
  I - Awaiting IIF ID allocation
  P - Pushed Session
  R - Removing User Profile (multi-line status for details)
  U - Applying User Profile (multi-line status for details)
  X - Unknown Blocker

**Comment by thaixuann** [comment]
Hello @micyew ,
Thanks for the device output. I will take care of it.

--Thai.

**Comment by thaixuann** [comment]
Hello @micyew ,
We fixed the issue and a genie beta package v19.10.1b3 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install genie.libs.parser --upgrade --pre

Thanks,
--Thai.

**Comment by micyew** [comment]
Bingo!!...All spot on.....Thanks for the update!!!

**Comment by thaixuann** [comment]
Thanks @micyew for the feedback. Great to hear. I will close this issue.

--Thai.

**Comment by micyew** [comment]
Hi Thai,

Sorry to bother again...Not sure should I open a new issue/request or
continue from here....

See...I have this c3850 running IOS 03.07.05E...This IOS version don't have
the "*show authentication sessions interface xxx details*"...It's
equivalent is "*show access-session interface xxxx details*" (see below CLI
output)...

But seems that the genie parser don't have a parser for "show
access-session *interface xxx*" (it only have "show access-session").

Are we able to create one for " show access-session interface xxxx details"?

Thanks

###
NAC_SW_375#sh ver | in Cisco IOS
Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software
(CAT3K_CAA-UNIVERSALK9-M), Version 03.07.05E RELEASE SOFTWARE (fc1)
Cisco IOS-XE software, Copyright (c) 2005-2015 by cisco Systems, Inc.
All rights reserved.  Certain components of Cisco IOS-XE software are
NAC_SW_375#
NAC_SW_375#
NAC_SW_375#show authen
NAC_SW_375#show authen?
% Unrecognized command
NAC_SW_375#show access?
access-lists  access-session

NAC_SW_375#show access-session ?
  cache          Shows Auth Manager cache info
  database       only show data stored in session database
  fqdn           FQDN Display Config commands
  handle         The context handle
  history        Show historic information
  interface      Client interface
  mac            The client MAC address
  method         The name of the Authentication method
  registrations  Shows Auth Manager registrations
  session-id     The client session ID
  |              Output modifiers
  <cr>

NAC_SW_375#show access-session interf
NAC_SW_375#show access-session interface Gi1/0/21 ?
  details  Show detailed information
  policy   Show policies applied on the interface
  |        Output modifiers
  <cr>

NAC_SW_375#show access-session interface Gi1/0/21 det
NAC_SW_375#show access-session interface Gi1/0/21 details
            Interface:  GigabitEthernet1/0/21
               IIF-ID:  0x105B0C0000005F5
          MAC Address:  0800.37c8.2dbc
         IPv6 Address:  Unknown
         IPv4 Address:  10.10.10.1
            User-Name:  08-00-37-C8-2D-BC
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
      Restart timeout:  N/A
    Common Session ID:  0A7820020000413CCCE37640
      Acct Session ID:  0x00007EAF
               Handle:  0x7100056D
       Current Policy:  Test_DOT1X-DEFAULT_V1

Server Policies:
              ACS ACL:  xACSACLx-IP-Test_ACL_XeroxPrinters_v1-597a95c4

Method status list:
       Method           State
       dot1x            Stopped
       mab              Authc Success
###

**Comment by thaixuann** [comment]
Hello @micyew<mailto:notifications@github.com>,
I opened a new issue here: https://github.com/CiscoTestAutomation/genieparser/issues/58

I will take a look and update you.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by micyew** [comment]
Hi Thai,

Apologies again....Not sure is issue 24 still having a parsing bug...

See...I ran the "show authentication sessions interface xxx details" on the
another test NAC switch. One interface return an error and the other
interface return good result!! Below is the genie parse result and the
switch actual CLI outcome.

I think the culprit is the fields *"Security Policy:  None Security"*
and *"Status:
 Link Unsecured"*. Those interfaces having these 2 fields gives an error
when running the parser..Those without return good result...

Seems that we need to include these fields in the "show authentication
sessions interface xxx details" ??

Thanks


PyATS$ genie parse "show authentication sessions interface
GigabitEthernet1/0/6 details" --testbed-file
testbed_c3850_authentication_session.yaml --device Test_NAC_SW
  0%|

                                                              | 0/1
[00:00<?, ?it/s]Issue with the parser show authentication sessions
interface GigabitEthernet1/0/6 details


Traceback (most recent call last):
  File "src/genie/cli/commands/parser.py", line 289, in
genie.cli.commands.parser.ParserCommand.parse
  File "src/genie/conf/base/device.py", line 528, in
genie.conf.base.device.Device.parse
  File "src/genie/metaparser/_metaparser.py", line 302, in
genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in
genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 392, in
genie.metaparser.util.schemaengine.Schema.validate
*genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys:
[['interfaces', 'GigabitEthernet1/0/6', 'mac_address', '0024.9b47.bf33',
'local_policies', 'template']]*
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ|
1/1 [00:00<00:00,  1.30it/s]


PyATS$ genie parse "show authentication sessions interface
GigabitEthernet1/0/48 details" --testbed-file
testbed_c3850_authentication_session.yaml --device Test_NAC_SW
  0%|

                                                              | 0/1
[00:00<?, ?it/s]{
  "interfaces": {
    "GigabitEthernet1/0/48": {
      "mac_address": {
        "006b.f16b.efa0": {
          "acct_session_id": "0x00004d7a",
          "common_session_id": "0A788905000021FBF8593E6C",
          "current_policy": "Test_DOT1X-DEFAULT_V1",
          "domain": "DATA",
          "handle": "0xa60001eb",
          "iif_id": "0x1AE25879",
          "ipv4_address": "10.1.1.1",
          "ipv6_address": "fe80::26b:f1ff:fe6b:efa0",
          "method_status": {
            "dot1x": {
              "method": "dot1x",
              "state": "Stopped"
            },
            "mab": {
              "method": "mab",
              "state": "Authc Success"
            }
          },
          "oper_control_dir": "both",
          "oper_host_mode": "multi-auth",
          "server_policies": {
            "1": {
              "name": "ACS ACL",
              "policies": "xACSACLx-IP-Test_ACL_WAPs-598d0d01"
            }
          },
          "session_timeout": {
            "type": "N/A"
          },
          "status": "Authorized",
          "user_name": "00-6B-F1-6B-EF-A0"
        }
      }
    }
  }
}
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ|
1/1 [00:00<00:00,  1.19it/s]


####

Test_NAC_SW#show authentication sessions interface GigabitEthernet1/0/6
details
            Interface:  GigabitEthernet1/0/6
               IIF-ID:  0x1FB8CAD0
          MAC Address:  0024.9b47.bf33
         IPv6 Address:  fe80::594c:9c65:7aa6:95a4
         IPv4 Address:  10.1.1.2
            User-Name:  User1
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A788905000029BE6BFF02FE
      Acct Session ID:  0x00004bca
               Handle:  0x010009d6
       Current Policy:  Test_DOT1X-DEFAULT_V1


Server Policies:
              ACS ACL: xACSACLx-IP-Test_ACL_PERMIT_ALL-565bad69

*      Security Policy:  None      Security Status:  Link Unsecured*


Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped

Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped

####


Test_NAC_SW#show authentication sessions interface GigabitEthernet1/0/48
details
            Interface:  GigabitEthernet1/0/48
               IIF-ID:  0x1AE25879
          MAC Address:  006b.f16b.efa0
         IPv6 Address:  fe80::26b:f1ff:fe6b:efa0
         IPv4 Address:  10.1.1.1
            User-Name:  00-6B-F1-6B-EF-A0
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A788905000021FBF8593E6C
      Acct Session ID:  0x00004d7a
               Handle:  0xa60001eb
       Current Policy:  Test_DOT1X-DEFAULT_V1


Server Policies:
              ACS ACL: xACSACLx-IP-Test_ACL_WAPs-598d0d01


Method status list:
       Method           State
        dot1x           Stopped
          mab           Authc Success

Test_NAC_SW#

###

**Comment by thaixuann** [comment]
Hi @micyew ,
I will take a look.

Thanks,
--Thai.

**Comment by micyew** [comment]
Hi Thai,

I've found another issue...There are cases where one switchport have two
NAC sessions!!

This occur when we connect a Cisco IP Phone to the switchport and the
laptop/PC "piggy back/daisy chain" to the back of the IP Phone...As you can
see below the switch CLI output...The port Gi1/0/17 have two different "ACS
ACL:"...

Hope the parser are able to capture this type of connections as well....

Test_NAC_SW#sh authentication sessions int *Gi1/0/17* details
            Interface:  *GigabitEthernet1/0/17*
               IIF-ID:  0x11910563
          MAC Address:  00e1.6d14.958a
         IPv6 Address:  Unknown
         IPv4 Address:  Unknown
            User-Name:  00-E1-6D-14-95-8A
               Status:  Authorized
               Domain:  VOICE
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A8628020000003463B40D0F
      Acct Session ID:  0x00000028
               Handle:  0x3000002a
       Current Policy:  Test_DOT1X-DEFAULT_V1


Server Policies:
              *ACS ACL: xACSACLx-IP-Test_ACL_CiscoPhones-583e3751*


Method status list:
       Method           State
        dot1x           Stopped
          mab           Authc Success

----------------------------------------

            Interface:  *GigabitEthernet1/0/17*
               IIF-ID:  0x1534B4E2
          MAC Address:  0024.9b47.c281
         IPv6 Address:  Unknown
         IPv4 Address:  Unknown
            User-Name:  host/Laptop123.test.com
               Status:  Authorized
               Domain:  DATA
       Oper host mode:  multi-auth
     Oper control dir:  both
      Session timeout:  N/A
    Common Session ID:  0A8628020000007168945FE6
      Acct Session ID:  0x0000008d
               Handle:  0x86000067
       Current Policy:  Test_DOT1X-DEFAULT_V1


Server Policies:
              *ACS ACL:* *xACSACLx-IP-Test_ACL_PERMIT_ALL-565bad69*
      Security Policy:  None
      Security Status:  Link Unsecured


Method status list:
       Method           State
        dot1x           Authc Success
          mab           Stopped

**Comment by thaixuann** [comment]
Hello,
Thanks for reporting. We will take a look.

Thanks,

Thai Nguyen
Core Software Group (CSG)  - SSR | Genie
DevX Engineering Community http://devx.cisco.com<http://devx.cisco.com/>

2018 Pioneer Award Winner -
Devx Pervasive Quality Platform with pyATS & Genie

**Comment by thaixuann** [comment]
Hello @micyew ,
We fixed the issue and genie package v19.11.1b1 has been released with the fix.
Could you please run the following command and try again to see if it works?

pip install --upgrade --pre genie.libs.parser

Or you can upgrade the whole Genie package with the latest version with this command
pip install genie --upgrade 

Please give a try and let's know.

Thanks,
--Thai.

**Comment by micyew** [comment]
(Not working):
Server Policies:
      Security Policy:  None
      Security Status:  Link Unsecured
              ACS ACL: xACSACLx-IP-Test_ACL_PERMIT_ALL-565bad69

(Working):
Server Policies:
          ACS ACL: xACSACLx-IP-Test_ACL_PERMIT_ALL-565bad69
      Security Policy:  None
      Security Status:  Link Unsecured

**Comment by thaixuann** [comment]
Hello @micyew ,
Thanks for the update. Will take a look.

--Thai.
