### ISSUE TITLE
ios "show module"  -Parser Output is empty

### ISSUE THREAD

**Issue by urskog84** [CiscoTestAutomation/genieparser#28]
In [7]: sw2.parse("show module")
[2019-08-21 10:48:21,959] +++ tstipswi002: executing command 'show module' +++
show module
Chassis Type : WS-C4507R+E

Power consumed by backplane : 40 Watts

Mod Ports Card Type                              Model              Serial No.
---+-----+--------------------------------------+------------------+-----------
 1    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE1747099J
 3     6  Sup 7L-E 10GE (SFP+), 1000BaseX (SFP)  WS-X45-SUP7L-E     CAT1745L39S
 6    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE201200M0
 7    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE180604R8

 M MAC addresses                    Hw  Fw           Sw               Status
--+--------------------------------+---+------------+----------------+---------
 1 24e9.b312.de30 to 24e9.b312.de5f 3.1                               Ok
 3 885a.92d1.aac0 to 885a.92d1.aac5 3.0 15.0(1r)SG10 03.06.07.E       Ok
 6 00f2.8b92.bf4e to 00f2.8b92.bf7d 3.1                               Ok
 7 b838.6144.4420 to b838.6144.444f 3.1                               Ok

Mod  Redundancy role     Operating mode      Redundancy status
----+-------------------+-------------------+----------------------------------
 3   Active Supervisor   RPR                 Active

System Failures:
----------------
Power Supply:   bad/off (see 'show power')

tstipswi002#
---------------------------------------------------------------------------
SchemaEmptyParserError                    Traceback (most recent call last)
<ipython-input-7-3c6a369ace5a> in <module>
----> 1 sw2.parse("show module")

/usr/local/lib64/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/util/schemaengine.cpython-37m-x86_64-linux-gnu.so in genie.metaparser.util.schemaengine.Schema.validate()

SchemaEmptyParserError: Parser Output is empty

**Comment by jeaubin** [comment]
Thanks, we will look into it.

**Comment by jeaubin** [comment]
It has been fixed, It will be part of the next release which is planned for next week.

**Comment by urskog84** [comment]
in witch release will the fix be included?
after upgrade `#pip3 install genie.libs.parser --upgrade --pre`
i get version - `genie.libs.parser            19.7.1b5`

still the same problem

/Petter

**Comment by urskog84** [comment]
I still have the issue in the 19.8 releas.

```
 pip3 list | grep parser
genie.libs.parser            19.8
genie.metaparser             19.8
genie.parsergen              19.8
```

error output
```
[2019-08-28 05:30:51,299] +++ tstipswi002: executing command 'show module' +++
show module
Chassis Type : WS-C4507R+E

Power consumed by backplane : 40 Watts

Mod Ports Card Type                              Model              Serial No.
---+-----+--------------------------------------+------------------+-----------
 1    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE1747099J
 3     6  Sup 7L-E 10GE (SFP+), 1000BaseX (SFP)  WS-X45-SUP7L-E     CAT1745L39S
 6    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE201200M0
 7    48  10/100/1000BaseT Premium POE E Series  WS-X4648-RJ45V+E   JAE180604R8

 M MAC addresses                    Hw  Fw           Sw               Status
--+--------------------------------+---+------------+----------------+---------
 1 24e9.b312.de30 to 24e9.b312.de5f 3.1                               Ok
 3 885a.92d1.aac0 to 885a.92d1.aac5 3.0 15.0(1r)SG10 03.06.07.E       Ok
 6 00f2.8b92.bf4e to 00f2.8b92.bf7d 3.1                               Ok
 7 b838.6144.4420 to b838.6144.444f 3.1                               Ok

Mod  Redundancy role     Operating mode      Redundancy status
----+-------------------+-------------------+----------------------------------
 3   Active Supervisor   RPR                 Active

System Failures:
----------------
Power Supply:   bad/off (see 'show power')

tstipswi002#
---------------------------------------------------------------------------
SchemaEmptyParserError                    Traceback (most recent call last)
/git/pyats_version_test/inventering.py in <module>
     33 for device in device_list:
     34     log.info("parse command in '{d}'".format(d=device.name))
---> 35     inv_data = device.parse('show module')
     36     all_data[device.name] = inv_data
     37

/usr/local/lib64/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/util/schemaengine.cpython-37m-x86_64-linux-gnu.so in genie.metaparser.util.schemaengine.Schema.validate()

SchemaEmptyParserError: Parser Output is empty

```

**Comment by urskog84** [comment]
same issue:
```
In [15]: sw2.os
Out[15]: 'iosxe'

In [16]: sw2.platform
Out[16]: 'cat4k'
```

**Comment by urskog84** [comment]
Not not so easy to send the testbed.yml to you. 
I have built a custom module as converts a ansible inventory to a pyats testbed file.

https://github.com/urskog84/pyats_version_test/blob/master/testbed_from_inventory.py

for testing right now i have to add/change the attributes manual in ipyathon termianl :(

```
In [37]: sw2.os
Out[37]: 'iosxe'

In [38]: sw2.platform
Out[38]: 'cat4k'

In [39]: sw2.custom
Out[39]: AttrDict({'abstraction': {'order': ['os', 'platform']}})

In [40]: sw2.parse('show module', output=output)
---------------------------------------------------------------------------
SchemaEmptyParserError                    Traceback (most recent call last)
<ipython-input-40-3f8396a34358> in <module>
----> 1 sw2.parse('show module', output=output)

/usr/local/lib64/python3.7/site-packages/genie/conf/base/device.cpython-37m-x86_64-linux-gnu.so in genie.conf.base.device.Device.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/_metaparser.cpython-37m-x86_64-linux-gnu.so in genie.metaparser._metaparser.MetaParser.parse()

/usr/local/lib64/python3.7/site-packages/genie/metaparser/util/schemaengine.cpython-37m-x86_64-linux-gnu.so in genie.metaparser.util.schemaengine.Schema.validate()

SchemaEmptyParserError: Parser Output is empty
```

**Comment by urskog84** [comment]
hmmm 😅. after `sw2.disconnect()` and `sw2.connect().` it works!!

great work team!!!!
