### ISSUE TITLE
After the update 21.8 I am still getting inaccurate numbers on some of my routers. for show bgp neighbors {all} advertised-routes

### ISSUE THREAD

**Issue by mupchu** [CiscoTestAutomation/genieparser#552]
After the update I am still getting inaccurate numbers on some of my routers.

_Originally posted by @mupchu in https://github.com/CiscoTestAutomation/genieparser/issues/486#issuecomment-938760055_

**Comment by mupchu** [comment]
I have not seen or heard anything on this . . .

I have a regex string that would capture all the values I do need, but I am not sure how to unpack everything going on in the parser:

(?P<Status>\*>)\s+(?P<network>\S+)\s+(?P<next_hop>\S+)\s(?P<metric>\s+\S+\s)?(?P<weight>\s+\S+\s)?(?P<as_path>.*)'

**Comment by danielgraziano** [comment]
@mupchu Terribly sorry for the delay. It seems this has gotten lost due to some error in tracking all the support cases. I am looking into this and will get back to you today.

**Comment by danielgraziano** [comment]
``` python
>>> len(out['vrf']['default']['neighbor']['192.168.248.25']['address_family']['ipv4 unicast']['advertised'].keys())
161
```
👍 

Let me generate a beta package so you can test it out

**Comment by danielgraziano** [comment]
@mupchu please upgrade to version 21.10 using `pip install --upgrade pyats[full]`. Then install the beta package using `pip install --upgrade --pre genie.libs.parser`. The version shown in `pip list` for genie.libs.parser should be 21.10.2b0

**Comment by mupchu** [comment]
I tested this on one of the routers that was having an issue, give me till the end of the day and i'll validate on a larger pool of devices.

thanks!

**Comment by mupchu** [comment]
So there is still an issue, it is mainly due to the formatting of the command:

cr1-mdf-main-mfh#sh bgp all neighbors 192.168.244.73 advertised-routes 
For address family: IPv4 Unicast
BGP table version is 480469, local router ID is 10.250.85.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal, 
              r RIB-failure, S Stale, m multipath, b backup-path, f RT-Filter, 
              x best-external, a additional-path, c RIB-compressed, 
              t secondary path, L long-lived-stale,
Origin codes: i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

     Network          Next Hop            Metric LocPrf Weight Path
 *>i  10.1.107.26/32   10.250.85.2              0    300      0 65082 65082 65082 65090.1 i
 *>i  10.1.107.32/32   10.250.85.2         130816    300      0 65081 ?
 *>i  10.1.107.33/32   10.250.85.2         130816    300      0 65081 ?
 *>i  10.1.107.51/32   10.250.85.2         130816    300      0 65082 ?
 *>i  192.168.204.0/30 10.250.85.2              0    300      0 65083 ?
 *>i  192.168.204.4/30 10.250.85.2              0    300      0 65083 ?
 *>i  192.168.204.8/30 10.250.85.2              0    300      0 65083 ?
 *>i  192.168.204.12/30
                      10.250.85.2              0    300      0 65083 ?
 *>i  192.168.204.16/30
                      10.250.85.2            768    300      0 65083 ?

what I noticed when trying to use parsergen is the wrap around values sometimes have a carriage return which screws up the table.

example:
 ' *>i  10.202.180.0/26  10.250.85.2           3072    300      0 65081 ?\r\n'
 ' *>i  10.202.180.64/26 10.250.85.2           3072    300      0 65081 ?\r\n'
 ' *>i  10.202.180.128/26\r\n'
 '                      10.250.85.2           3072    300      0 65081 ?\r\n'
 ' *>i  10.202.180.192/26\r\n'
 '                      10.250.85.2           3072    300      0 65081 ?\r\n'

10.202.180.128/26, and 10.202.180.192/26 both don't appear in the dictionary

as a temp hack I am pulling the raw table and modifying it before I put it into parsergen, so I can get part of the table but it is proving to be difficult.

**Comment by mupchu** [comment]
Let me know if you need me to pull some logs or files . . . not sure what you will want to see,

**Comment by danielgraziano** [comment]
Parsergen? I'm confused. We dont use parsergen in this parser (it wont work because the output can be continued on the next line.

Are you saying that <dev>.parse() with the beta package is still not working? If so can you please provide the device output  and point out which lines are not being parsed?

**Comment by mupchu** [comment]
Sorry I am probably adding to the confusion:

there are about 100ish routes missing, a few examples are:
10.202.180.128/26
10.202.180.192/26
192.168.244.188/30

attached is the raw output from the command, the log for the device in pyats, and lastly a print of the resulting dictionary.

[print_dictionary_out.txt](https://github.com/CiscoTestAutomation/genieparser/files/7635402/print_dictionary_out.txt)
[cr1-mdf-main-mfh-cli-1638373706.log](https://github.com/CiscoTestAutomation/genieparser/files/7635403/cr1-mdf-main-mfh-cli-1638373706.log)
[my_output_raw.txt](https://github.com/CiscoTestAutomation/genieparser/files/7635404/my_output_raw.txt)

What I mentioned about parsergen, is my attempt to work around the parsing issue so i can get a report out to my managers.  It is just highlighting some of the difficulties in parsing out this particular command.  In particular the wrap-around values seem to be causing most of the issues.

**Comment by danielgraziano** [comment]
Do you happen to have any term length commands configured that could cause excessive output wrapping?

**Comment by mupchu** [comment]
no term is default and pyats also configures the length and width as part of the connect process:

cr1-mdf-main-mfh#

2021-12-01 15:48:26,832: %UNICON-INFO: +++ initializing handle +++

2021-12-01 15:48:26,899: %UNICON-INFO: +++ cr1-mdf-main-mfh with alias 'cli': executing command 'term length 0' +++
term length 0
cr1-mdf-main-mfh#

2021-12-01 15:48:27,357: %UNICON-INFO: +++ cr1-mdf-main-mfh with alias 'cli': executing command 'term width 0' +++
term width 0
cr1-mdf-main-mfh#

the attachments were just thrown in notepad so they don't handle the carriage returns the same, and that output was missing from the logs.

**Comment by danielgraziano** [comment]
``` python
>>> len(out['vrf']['default']['neighbor']['192.168.248.25']['address_family']['ipv4 unicast']['advertised'].keys())
927
```

I just released a new beta package (version 21.10.2b1). Please upgrade using `pip install --upgrade --pre genie.libs.parser` and let me know if you see any problems.

**Comment by mupchu** [comment]
much closer now there were a couple routes still missing but it is a little odd.

10.32.0.0/16 is included in the dictionary, 

10.32.220.0/24 missing
10.32.221.0/24 missing
10.32.240.0/23 missing

we are getting the summary, but not the more specific routes being advertised.

[cr2-mdf-main-sjmc-cli-1638475221.log](https://github.com/CiscoTestAutomation/genieparser/files/7644824/cr2-mdf-main-sjmc-cli-1638475221.log)
[dict_output_sjmc.txt](https://github.com/CiscoTestAutomation/genieparser/files/7644825/dict_output_sjmc.txt)

**Comment by danielgraziano** [comment]
Fixed that up, let me fix the unittests, get the PR reviewed, then ill release another beta

**Comment by mupchu** [comment]
sounds good thanks!

**Comment by danielgraziano** [comment]
Released a new beta package version 21.10.2b2. Please upgrade using the same command

**Comment by mupchu** [comment]
looks like that fixed everything.  

thanks for looking into this!

**Comment by danielgraziano** [comment]
Perfect! For now use the beta package. It will be included in the next release (version 21.12 this December).
